
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name:  Erik Assum
url: http://slipset.github.io
description: My blog.
twitter: slipset
github: slipset
gravatar_url: images/cloud.001.png
highlighter: rouge
