pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name:  Erik Assum
url: http://slipset.github.io
description: A fantastic blog that is fantastic.
twitter: slipset
github: slipset
gravatar_url: images/cloud.001.png
